 const tableImage = [
   {
     quantite: 1,
     id: 1,
     name: "Gateau Item",
     prix: 5,
     photo: "./imagCart/1.jpeg",
   },
   {
     quantite: 1,
     id: 2,
     name: "Gateau Item",
     prix: 15,
     photo: "./imagCart/2.jpeg",
   },
   {
     quantite: 1,
     id: 3,
     name: "Gateau Item",
     prix: 10.0,
     photo: "./imagCart/3.avif",
   },
   {
    quantite: 1,
     id: 4,
     name: "Gateau Item",
     prix: 15,
     photo: "./imagCart/4.avif",
   },
   {
    quantite: 1,
     id: 5,
     name: "Gateau Item",
     prix: 5.0,
     photo: "./imagCart/5.jpeg",
   },
   {
    quantite: 1,
     id: 6,
     name: "Gateau Item",
     prix: 6.0,
     photo: "./imagCart/6.webp",
   },
   {
    quantite: 1,
     id: 7,
     name: "Cupcake item",
     prix: 8,
     photo: "./imagCart/7.jpeg",
   },
   {
    quantite: 1,
     id: 8,
     name: "Cupcake item",
     prix: 18,
     photo: "./imagCart/8.jpeg",
   },
   {
    quantite: 1,
     id: 9,
     name: "Cupcake item",
     prix: 12,
     photo: "./imagCart/9.jpeg",
   },
   {
    quantite: 1,
     id: 10,
     name: "Cupcake item",
     prix: 7,
     photo: "./imagCart/10.jpeg",
   },
   {
    quantite: 1,
     id: 11,
     name: "Cupcake item",
     prix: 9,
     photo: "./imagCart/11.jpeg",
   },
   {
    quantite: 1,
     id: 12,
     name: "Cupcake item",
     prix: 16.0,
     photo: "./imagCart/12.jpeg",
   },
   {
    quantite: 1,
     id: 13,
     name: "cakes item",
     prix: 10.0,
     photo: "./imagCart/13.webp",
   },
   {
    quantite: 1,
     id: 14,
     name: "cakes item",
     prix: 13.0,
     photo: "./imagCart/14.jpeg",
   },
   {
    quantite: 1,
     id: 15,
     name: "cakes item",
     prix: 5.0,
     photo: "./imagCart/15.webp",
   },
   {
    quantite: 1,
     id: 16,
     name: "cakes item",
     prix: 14.0,
     photo: "./imagCart/16.jpeg",
   },
   {
    quantite: 1,
     id: 17,
     name: "cakes item",
     prix: 12,
     photo: "./imagCart/17.webp",
   },
   {
    quantite: 1,
     id: 18,
     name: "cakes item",
     prix: 7,
     photo: "./imagCart/18.avif",
   },
   {
    quantite: 1,
     id: 19,
     name: "sweet item",
     prix: 3,
     photo: "./imagCart/19.jpeg",
   },
   {
    quantite: 1,
     id: 20,
     name: "sweet item",
     prix: 4,
     photo: "./imagCart/20.jpeg",
   },
   {
    quantite: 1,
     id: 21,
     name: "sweet item",
     prix: 8,
     photo: "./imagCart/21.webp",
   },
   {
    quantite: 1,
     id: 22,
     name: "doughnut item",
     prix: 5,
     photo: "./imagCart/22.jpeg",
   },
   {
    quantite: 1,
     id: 23,
     name: "doughnut item",
     prix: 7,
     photo: "./imagCart/23.jpeg",
   },
   {
    quantite: 1,
     id: 24,
     name: "doughnut item",
     prix: 9,
     photo: "./imagCart/19.jpg",
   },
 ];
